<a href="https://colab.research.google.com/github/LR2023O/DATA-SCIENCE/blob/main/Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
larry = pd.read_csv('/content/Road.csv')
print("Shape of the dataset:", larry.shape)
larry.head(28)


Shape of the dataset: (12316, 32)


Time Day_of_week Age_band_of_driver Sex_of_driver   Educational_level  \
0   17:02:00      Monday              18-30          Male   Above high school   
1   17:02:00      Monday              31-50          Male  Junior high school   
2   17:02:00      Monday              18-30          Male  Junior high school   
3    1:06:00      Sunday              18-30          Male  Junior high school   
4    1:06:00      Sunday              18-30          Male  Junior high school   
5   14:15:00      Friday              31-50          Male                 NaN   
6   17:30:00   Wednesday              18-30          Male  Junior high school   
7   17:20:00      Friday              18-30          Male  Junior high school   
8   17:20:00      Friday              18-30          Male  Junior high school   
9   17:20:00      Friday              18-30          Male  Junior high school   
10  14:40:00    Saturday              18-30          Male   Above high school   
11  14:40:00    Saturday              31-50          Male   Above high school   
12  17:45:00    Thursday              18-30          Male  Junior high school   
13  17:45:00    Thursday              31-50          Male  Junior high school   
14  17:45:00    Thursday              31-50          Male  Junior high school   
15  22:45:00      Monday              18-30        Female  Junior high school   
16  22:45:00      Monday              18-30          Male  Junior high school   
17  22:45:00      Monday              18-30          Male   Elementary school   
18  22:45:00      Monday              18-30          Male  Junior high school   
19   8:20:00     Tuesday              18-30          Male  Junior high school   
20   8:20:00     Tuesday           Under 18          Male  Junior high school   
21  15:10:00    Thursday              18-30          Male  Junior high school   
22  12:11:00    Thursday              18-30          Male   Elementary school   
23  12:11:00    Thursday              31-50          Male  Junior high school   
24  18:36:00   Wednesday              18-30          Male                 NaN   
25  18:36:00   Wednesday              18-30          Male  Junior high school   
26  18:36:00   Wednesday              18-30       Unknown  Junior high school   
27  14:35:00      Friday              18-30          Male   Above high school   

   Vehicle_driver_relation Driving_experience       Type_of_vehicle  \
0                 Employee              1-2yr            Automobile   
1                 Employee         Above 10yr   Public (> 45 seats)   
2                 Employee              1-2yr       Lorry (41?100Q)   
3                 Employee             5-10yr   Public (> 45 seats)   
4                 Employee              2-5yr                   NaN   
5                  Unknown                NaN                   NaN   
6                 Employee              2-5yr            Automobile   
7                 Employee              2-5yr            Automobile   
8                 Employee         Above 10yr       Lorry (41?100Q)   
9                 Employee              1-2yr            Automobile   
10                   Owner              1-2yr  Public (13?45 seats)   
11                Employee         No Licence            Automobile   
12                Employee              1-2yr   Public (> 45 seats)   
13                Employee             5-10yr       Lorry (41?100Q)   
14                Employee         Above 10yr            Automobile   
15                Employee         Above 10yr        Lorry (11?40Q)   
16                   Owner             5-10yr  Public (13?45 seats)   
17                Employee              2-5yr  Public (13?45 seats)   
18                Employee              2-5yr                   NaN   
19                Employee          Below 1yr            Long lorry   
20                Employee              2-5yr       Lorry (41?100Q)   
21                Employee              2-5yr        Lorry (11?40Q)   
22                Employe

In [ ]:
import pandas as pd
larry = pd.read_csv('/content/Road.csv')
data = larry.loc[:, ['Age_band_of_driver', 'Driving_experience', 'Type_of_vehicle',
                     'Cause_of_accident', 'Accident_severity']]
data.head(28)

Age_band_of_driver Driving_experience       Type_of_vehicle  \
0               18-30              1-2yr            Automobile   
1               31-50         Above 10yr   Public (> 45 seats)   
2               18-30              1-2yr       Lorry (41?100Q)   
3               18-30             5-10yr   Public (> 45 seats)   
4               18-30              2-5yr                   NaN   
5               31-50                NaN                   NaN   
6               18-30              2-5yr            Automobile   
7               18-30              2-5yr            Automobile   
8               18-30         Above 10yr       Lorry (41?100Q)   
9               18-30              1-2yr            Automobile   
10              18-30              1-2yr  Public (13?45 seats)   
11              31-50         No Licence            Automobile   
12              18-30              1-2yr   Public (> 45 seats)   
13              31-50             5-10yr       Lorry (41?100Q)   
14              31-50         Above 10yr            Automobile   
15              18-30         Above 10yr        Lorry (11?40Q)   
16              18-30             5-10yr  Public (13?45 seats)   
17              18-30              2-5yr  Public (13?45 seats)   
18              18-30              2-5yr                   NaN   
19              18-30          Below 1yr            Long lorry   
20           Under 18              2-5yr       Lorry (41?100Q)   
21              18-30              2-5yr        Lorry (11?40Q)   
22              18-30             5-10yr       Lorry (41?100Q)   
23              31-50         Above 10yr     Public (12 seats)   
24              18-30                NaN                   NaN   
25              18-30              2-5yr                  Taxi   
26              18-30             5-10yr                   NaN   
27              18-30              2-5yr            Automobile   

                     Cause_of_accident Accident_severity  
0                      Moving Backward     Slight Injury  
1                           Overtaking     Slight Injury  
2            Changing lane to the left    Serious Injury  
3           Changing lane to the right     Slight Injury  
4                           Overtaking     Slight Injury  
5                          Overloading     Slight Injury  
6                                Other     Slight Injury  
7               No priority to vehicle     Slight Injury  
8           Changing lane to the right     Slight Injury  
9                      Moving Backward    Serious Injury  
10           Changing lane to the left    Serious Injury  
11           No priority to pedestrian    Serious Injury  
12                       No distancing     Slight Injury  
13              No priority to vehicle     Slight Injury  
14                       No distancing    Serious Injury  
15                       No distancing    Serious Injury  
16                     Moving Backward     Slight Injury  
17          Changing lane to the right    Serious Injury  
18           No priority to pedestrian     Slight Injury  
19                     Moving Backward    Serious Injury  
20  Getting off the vehicle improperly     Slight Injury  
21                          Overtaking    Serious Injury  
22                         Overloading    Serious Injury  
23          Changing lane to the right    Serious Injury  
24                    Improper parking     Slight Injury  
25                               Other     Slight Injury  
26           Changing lane to the left     Slight Injury  
27          Changing lane to the right     Slight Injury

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load the dataset
data = pd.read_csv('/content/Road.csv')

# Fill missing values (simple approach)
data = data.fillna('Unknown')

# Encode categorical features
le_features = {}
for col in ['Age_band_of_driver', 'Driving_experience', 'Type_of_vehicle', 'Cause_of_accident']:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    le_features[col] = le

# Encode target
le_target = LabelEncoder()
data['Accident_severity'] = le_target.fit_transform(data['Accident_severity'])

# Separate features and target
X = data[['Age_band_of_driver', 'Driving_experience', 'Type_of_vehicle', 'Cause_of_accident']]
y = data['Accident_severity']

# Split dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

# Print shapes
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

# Create Logistic Regression model
model = LogisticRegression(max_iter=1000)

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))


X_train shape: (9852, 4)
X_test shape: (2464, 4)
y_train shape: (9852,)
y_test shape: (2464,)
Accuracy: 0.8478084415584416
Confusion Matrix:
 [[   0    0   28]
 [   0    0  347]
 [   0    0 2089]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        28
           1       0.00      0.00      0.00       347
           2       0.85      1.00      0.92      2089

    accuracy                           0.85      2464
   macro avg       0.28      0.33      0.31      2464
weighted avg       0.72      0.85      0.78      2464



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)
print(regressor.intercept_)
print(regressor.coef_)
y_pred = regressor.predict(X_test)
y_pred
y_test.head(28)

1.8233205980952745
[ 0.00326442 -0.00355268  0.00069685  0.00112603]


10974    2
5748     2
4941     2
11832    2
8173     2
5453     1
7491     2
3728     2
1070     1
9124     1
4500     2
8408     2
4175     2
8228     1
2164     2
223      1
7437     2
10768    2
2027     2
10681    2
4696     2
717      2
3764     2
1307     2
11823    2
5528     1
10570    2
11249    2
Name: Accident_severity, dtype: int64

In [ ]:
from sklearn import metrics
import numpy as np

#Assuming y_test and y_pred are NumPy arrays or Pandas Series
mae = metrics.mean_absolute_error(y_test, y_pred)
mse = metrics.mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
 # RMSE is the square root of MSE
print(f"Mean Absolute Error (MAE): {mae:.3f}")
print(f"Mean Squared Error (MSE): {mse:.3f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.3f}")

Mean Absolute Error (MAE): 0.280
Mean Squared Error (MSE): 0.160
Root Mean Squared Error (RMSE): 0.400


In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# Load dataset
data = pd.read_csv('/content/Road.csv')

# Fill missing values
data = data.fillna('Unknown')

# Encode categorical features
le_features = {}
for col in ['Age_band_of_driver', 'Driving_experience', 'Type_of_vehicle', 'Cause_of_accident']:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    le_features[col] = le

le_target = LabelEncoder()
data['Accident_severity'] = le_target.fit_transform(data['Accident_severity'])

# Features and target
X = data[['Age_band_of_driver', 'Driving_experience', 'Type_of_vehicle', 'Cause_of_accident']]
y = data['Accident_severity']

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

# Print shapes
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

# Create and train Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate model
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

# Print metrics with 3 decimal places
print(f"Mean Absolute Error (MAE): {mae:.3f}")
print(f"Mean Squared Error (MSE): {mse:.3f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.3f}")


X_train shape: (9852, 4)
X_test shape: (2464, 4)
y_train shape: (9852,)
y_test shape: (2464,)
Mean Absolute Error (MAE): 0.280
Mean Squared Error (MSE): 0.160
Root Mean Squared Error (RMSE): 0.400


In [ ]:
import joblib
import pickle  # Import the pickle module
from sklearn.linear_model import LinearRegression

#Train your linear regression model
model = LinearRegression()
model.fit(X_train,y_train)
#Save the trained model to a file using joblib
joblib.dump(model, 'linear_regression_model.pkl')

#Alternatively, you can save the model using pickle
with open('linear_regression_model.pkl', 'wb') as file:
  pickle.dump(model, file)

In [ ]:
import joblib
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Suppose this is your new sample (categorical values)
new_sample = pd.DataFrame({
    'Age_band_of_driver': ['18-30'],
    'Driving_experience': ['2-5yr'],
    'Type_of_vehicle': ['Automobile'],
    'Cause_of_accident': ['Overtaking']
})

for col in ['Age_band_of_driver', 'Driving_experience', 'Type_of_vehicle', 'Cause_of_accident']:
    le = le_features[col]  # LabelEncoder from training
    new_sample[col] = le.transform(new_sample[col])

# Convert to numpy array
new_X = new_sample.values

# Load the trained model
model = joblib.load('linear_regression_model.pkl')

# Make predictions
predictions = model.predict(new_X)

# Create a DataFrame to display the sample and predicted value
new_data = new_sample.copy()
new_data['Predicted_Accident_Severity'] = predictions

print(new_data)


   Age_band_of_driver  Driving_experience  Type_of_vehicle  Cause_of_accident  \
0                   0                   1                0                 16   

   Predicted_Accident_Severity  
0                     1.837784  


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
